route_default:  
    logging: req, req_body(POST,PUT), resp_body(POST)
    metric: "test.http_proxy.{server_name}.{verb}_{route_name}_{response_code}"

server_default:
    balancer: rr
    health: 'off'

servers:
    - name: dummy_server
      target: 127.0.0.1:9999
      health : 'off'

    - name: ATSServiceServer
      target: test-sysapi.lunextelecom.com
      health : 'ping'
      
    - name: POSServiceServer
      target: test-api.lunextelecom.com
      health : 'ping'

routes: 
    - name: dummy_checkhealth
      url: "GET /http_proxy/.*"
      server: dummy_server
      logging: 'off'
      metric: 'off'
      
    - name: AtsService
      url: "GET /AtsService.svc/.*"
      server: ATSServiceServer
      logging: req(*), resp_body(*)

    - name: PosService
      url: "GET /PosService.svc/.*"
      server: POSServiceServer
      logging: req(*), resp_body(*)
  