route_default:  
    logging: req, req_body(POST,PUT), resp_body(POST)
    metric: "test.http_proxy.{server_name}.{verb}_{route_name}_{response_code}"

server_default:
    balancer: rr
    health: 'off'

servers:
    - name: health_server
      target: 10.9.9.62:9004
      health : /

    - name: dummy_server
      target: 192.168.93.61:9090/dummyws, 192.168.93.62:9090/dummyws
      health : /home

    - name: authen_server
      target: 10.9.9.62:8090, 10.9.9.61:8090,10.9.9.63:8090
      health : 'off'
      balancer: lu

routes: 
    - name: get_list
      url: "GET /list.*"
      server: health_server
      logging: req(*)
      metric: 'off'

    - name: get_health
      url: "GET /health"
      server: health_server
      logging: req, req_body(POST,PUT)
      metric: "test.http_proxy.{server_name}.{route_name}_{response_code}"

    - name: dummy_home
      url: "GET /home"
      server: dummy_server

    - name: dummy_authen
      url: "GET /authsvc.*"
      server: authen_server
      logging: 'off'
    