route_default:  
    logging: req, req_body(POST,PUT), resp_body(POST)
    metric: "test.http_proxy.{server_name}.{verb}_{route_name}_{response_code}"

server_default:
    balancer: rr
    health: 'off'

servers:
    - name: dummy_server
      target: 127.0.0.1:9999
      health : /http_proxy/checkhealth

    - name: AtsService_server
      target: test-sysapi.lunextelecom.com
      health : 'off'
      
routes: 
    - name: dummy_checkhealth
      url: "GET /http_proxy/checkhealth"
      server: dummy_server
      logging: 'off'
      health : 'off' 
      metric: 'off'
      
    - name: AtsService
      url: "GET /AtsService.*"
      server: AtsService_server
      logging: req(*)  
      health : 'off' 